Repository BrightCoders-Proyectos/tribo-web, pull requests merged in 2020-12, with the labels that each got.

#12 Feature#2/Tailwind CSS Setup
  app/assets/stylesheets/application.css
  app/javascript/packs/application.js
  app/javascript/tailwind.config.js
  app/views/layouts/application.html.erb
  package.json
  postcss.config.js
  yarn.lock
Labels: brightcoders approved, ready for review

#15 Enable Asset Pipeline
  Gemfile
  Gemfile.lock
  config/application.rb
  config/environments/production.rb
Labels: brightcoders approved, ready for review

#14 Modal
  app/controllers/legal_controller.rb
  app/javascript/packs/modal.js
  app/views/layouts/application.html.erb
  app/views/legal/index.html.erb
  config/application.rb
  config/locales/es.yml
  config/routes.rb
  test/controllers/legal_controller_test.rb
Labels: ready for review

#22 Sidebar menu
  .gitignore
  app/assets/images/tribo_logo.svg
  app/javascript/packs/modal.js
  app/javascript/packs/sidebar.js
  app/views/layouts/application.html.erb
  app/views/legal/index.html.erb
Labels: brightcoders approved

#16 Home Screen
  app/assets/images/logo.png
  app/assets/stylesheets/application.css
  app/controllers/home_controller.rb
  app/javascript/packs/application.js
  app/javascript/tailwind.config.js
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  test/controllers/home_controller_test.rb
Labels: brightcoders approved, ready for review

#33 Feature#26 Information Store Modal
  app/assets/images/bussines_marker.svg
  app/assets/images/close.svg
  app/javascript/packs/modal_info.js
  app/views/legal/index.html.erb
Labels: ready for review
